### ISSUE TITLE
Left join gives warning and unexpected result

### ISSUE THREAD

**Issue by jdsalchow** [zio/zio-protoquill#107]
**Version**: 3.16.5-Beta30
**Module**: `quill-jdbc`
**Database**: `h2` in the reproduction, but probably db independent

### Expected behavior

With the scheme
```scala
case class Foo(id: Int, attribute: String)
case class Bar(id: Int, fooId: Int, attribute: String)
```
and only `Foo(1, "a")` in the database I expect

```scala
for {
    foo <- query[Foo]
    bar <- query[Bar].leftJoin(bar => bar.fooId == foo.id)
  } yield (foo, bar)
```

to return

```scala
List((Foo(1,a),None))
```

and to get no compilation warnings.

### Actual behavior

I get the result
```scala
List((Foo(1,a),Some(Bar(0,0,null))))
```
and the compilation warning
```
[WARNING] Arity of product column "_2" type Option[Bar] was 0. This is not valid.
```

### Steps to reproduce the behavior

A reproduction project is at https://github.com/jdsalchow/quill-repro/blob/issue-107/src/main/scala/Main.scala

I was originally interested in Postgres and built this in h2 for the sake of a simple reproduction. I expect the issue to be in  the implicit resolution in `quill-sql/src/main/scala/io/getquill/generic/GenericDecoder.scala`.

### Workaround

I'm not aware of one.

@getquill/maintainers

**Comment by chriseteka** [comment]
Trying to follow up on this @jdsalchow, you mentioned having just one row (`Foo` data) in your DB. Then you ran a **SELECT** from `Bar` which has no data, **LEFT** joining it to `Foo` on `bar.fooId == foo.id`.

If there is no data in `Bar`, should this statement even return anything? Referencing the section where you said you expect `List((Foo(1,a),None))`

**Comment by jdsalchow** [comment]
Yes, that would be my expectation. For a more concrete example, if I left join `Person` and `Address` I expect to get all valid tuples `(Person, Address)` according to the join condition and all rows in `Person` for which there is no `Address` --- otherwise it would just be an inner join.

**Comment by deusaquilus** [comment]
I agree that the `(Foo(1,a),Some(Bar(0,0,null)))` is not the correct answer and that `(Foo(1,a),None)` is right since in this case the JDBC result-row is `Row(1, "a", null, null, null)` (i.e. if we were to take all the columns in the ResultSet and put them all into a `Row` object it would be that). 

The interesting question, is what if the result-row is `Row(1, "a", null, 1, null)`? My instinct here is that it should be `(Foo(1,a),Some(Bar(0,1,null)))`. Scala2-Quill however would decode it into `(Foo(1,a),None))`. In fact the only way for Scala2-Quill to not encode that value as `(Foo(1,a),None))` would be to make both `Bar.id` and `Bar.attribute` columns optional since Scala2-Quill makes an entirety of an `Option[Product]` element `None` if a single column contained inside has a null-value on the DB-level.

This is one of the Scala2-Quill functionalities that I did not know very well before so I needed to do quite a bit of analysis to reconstruct what is going on. Once I did, I realized that I want to fix the functionality in Scala2-Quill before implementing it here. You can have a look at details about the issue [here](https://github.com/zio/zio-quill/issues/2505) and the corresponding PR [here](https://github.com/zio/zio-quill/pull/2506).

Now since both of these are done, I will attempt to circle-back to making these changes in ProtoQuill.

**Comment by jdsalchow** [comment]
Thanks a lot for fixing this so quickly! Do you plan a release with the fix?

**Comment by deusaquilus** [comment]
Yeah, hopefully within the next few days.
