### ISSUE TITLE
quill-cassandra-zio example - Could not find Quill::Cassandra[+Literal] inside ZEnvironment

### ISSUE THREAD

**Issue by tbarabas** [zio/zio-protoquill#217]
I tried to pout this example into an sbt project, and it failed. https://github.com/zio/zio-protoquill/tree/master/quill-cassandra-zio/src/test/scala/io/getquill/context/cassandra/zio/examples

**Version**: (e.g. `4.6.0`)
**Module**: (e.g. `quill-cassandra-zio`)
**Database**: (e.g. `cassandra`)

### Expected behavior
Joe's name to be printed on the screen ( I created the database, the table, and added Joe)

### Actual behavior
Error printed on the screen, nothing else:

timestamp=2022-11-16T16:03:53.629398Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.Error: Defect in zio.ZEnvironment: Could not find Quill::Cassandra[+Literal] inside ZEnvironment(Quill$::Cassandra[+Literal] -> Cassandra(io.getquill.Literal$@1b2cbaef,CassandraZioSession(com.datastax.oss.driver.internal.core.session.DefaultSession@3312f26d,1000)))
        at zio.ZEnvironment$$anon$1.get(ZEnvironment.scala:167)
        at zio.ZIO$ServiceWithZIOPartiallyApplied$.apply$extension$$anonfun$13$$anonfun$1(ZIO.scala:5075)
        at <empty>.IdiomaticAppData.QueryService.live(IdiomaticAppData.scala:25)
        at <empty>.Main.run(IdiomaticApp.scala:10)
        at <empty>.Main.run(IdiomaticApp.scala:10)
        at <empty>.Main.run(IdiomaticApp.scala:10)
        at <empty>.Main.run(IdiomaticApp.scala:10)
        at <empty>.Main.run(IdiomaticApp.scala:10)
        at <empty>.Main.run(IdiomaticApp.scala:10)"

### Steps to reproduce the behavior
$ git pull https://github.com/tbarabas/scala3quill.git
$ sbt run

If the issue can be reproduced using a [mirror context](http://getquill.io/#contexts-mirror-context), please provide a scastie snippet that reproduces it. See https://scastie.scala-lang.org/fwbrasil/Z2CeR2qHQJK6EyQWUBhANA as an example. Remember to select the correct Quill version in the left menu.

### Workaround
I don't know any. Use scala 2. It did not work with any scala 3 version, although I tried java 8 and 17, quill-cassandra-zio 4.5.0 and  4.6.0, with the same result
@getquill/maintainers

**Comment by dylandoamaral** [comment]
It was working with zio 2.0.2, starting to fail since zio 2.0.3.

**Comment by deusaquilus** [comment]
Ouch! Will have a look as I can.

**Comment by ajrnz** [comment]
zio 2.0.5 doesn't seem to fix the problem either

I think the problem might be something in izumi-reflect. I get the same issue with Postgres:

```
Defect in zio.ZEnvironment: Could not find Quill::Postgres[+SnakeCase] inside ZEnvironment(Quill$::Postgres[+SnakeCase] -> io.getquill.jdbczio.Quill$Postgres@a2baa02)
```

as above downgrading to zio 2.0.2 fixes the issue

**Comment by csar** [comment]
> downgrading to zio 2.0.2 fixes the issue

until you have a library that depends on 2.0.3+, then you get the same with the  env values of that library. To me it feels like zio regression

**Comment by csar** [comment]
> To me it feels like zio regression

I talked to John about this, the regression comes from the newer version of [izumi-reflect](https://github.com/zio/izumi-reflect/releases/tag/v2.2.0)

**Comment by ElieBen-Shlomo** [comment]
Hey guys. I also ran into this problem, but found that downgrading `zio` to 2.0.2 didn't solve it. Here is a script/project that reproduces the problem with zio=2.0.2 and zio-http=0.0.3

https://github.com/ElieBen-Shlomo/zio-sandbox

Let me know if you get the same error message when running locally

**Comment by objektwerks** [comment]
Kindly allow me to be extremely unpopular.

A few years back, similar bug(s) plagued Quill.

Yet Quill authors were too busy working on a Scala 3 conversion and the like - or so the story went.

Consequently Quill users moved on to other solutions.

Once again, the same scenario presents itself. Why is that?

I'm simply trying to build a distributed ZIO prototype app --- and can't because of this ZIO-Quill bug.

Hopefully, I've offended those responsible for this bug.

Not to worry, though, take your time, because I've recommended to my client to pass on a ZIO solution.

Why don't you have a customer-first attitude?

**Comment by deusaquilus** [comment]
Dear @objektwerks I am sorry that the lack of movement on this issue has caused you to suggest against using the ZIO ecosystem. I am also sincerely sorry that you have not experienced the level of service that you would like to have and that a serious issue in the latest version of Quill has persisted for the span of one or multiple months.

Let me ask you a frank question. Which one of my personal commitments should I give up in order to work on this issue? How about my daughter's recital tomorrow? Or maybe taking my son to the mall on Sunday? I am already working until 2-3AM every night on the OSS ecosystem (with all the strain to my marriage and personal health that this brings!) trying to make things better for everyone, so in your estimation, what other actions are necessary?

Quill is a language-integrated platform that supports 8+ databases (across 5+ drivers). ProtoQuill is the same system re-built from the ground up. Fully maintaining these systems to the service-level of 1-2 weeks per every issue would take a dedicated staff of 2-3 developers. I have zero.

So again, I am sorry that you have experienced this issue and you are leaving the ZIO ecosystem because of it. I hope whatever technology you decided to adopt has the service levels that you require.

**Comment by csar** [comment]
> Hey guys. I also ran into this problem, but found that downgrading `zio` to 2.0.2 didn't solve it. Here is a script/project that reproduces the problem with zio=2.0.2 and zio-http=0.0.3
> 
> https://github.com/ElieBen-Shlomo/zio-sandbox

You need to exclude the transitive dependencies imported by zio-http, it overrides the 2.0.2 dependency of your project:
`libraryDependencies += "dev.zio" %% "zio-http" % "0.0.3" exclude("dev.zio", "zio_3") exclude("dev.zio", "zio-streams_3")`

I think we are in a weird situation: scala-steward recommends upgrading zio from 2.0.2 to the current 2.0 which is not a problem for a Scala 2 project, the breaking change in izumi-reflect appears only in Scala 3 compilations. So technically zio_2.13 2.0.3+ is correctly labelled, but the zio_3 is not

**Comment by csar** [comment]
> Why don't you have a customer-first attitude?

How much you pay for the Gold subscription with a strict SLA? - Thought so....

@deusaquilus it seems that upgrading to zio 2.0.5 isn't breaking anything, but I didn't manage to run all tests because of memory limits

**Comment by 987Nabil** [comment]
I am still confused where this has to be fixed. But I tried to force the newest version izumi-reflect and zio and still get this error. If there is a way to help to fix this, please point me to the right direction and I'll give it a try :)

**Comment by tbarabas** [comment]
thanks a lot
