### ISSUE TITLE
Running Query adds 'AS _1' decorators to returned fields apparently using Tuple field names

### ISSUE THREAD

**Issue by jeffgarratt** [zio/zio-protoquill#64]
**Version**: 3.16.0.Beta2.1
**Module**: quill-sql
**Database**: N/A
**scalaVersion**: 3.1.0 

### Expected behavior

The following code works as expected with version: 3.10.0.Beta1.6. I jumped to latest to test latest version.

I am using the mirror context only with Literal style.

with code 
````
given  ctx: SqlMirrorContext[io.getquill.MirrorSqlDialect.type, io.getquill.Literal.type] = new SqlMirrorContext(MirrorSqlDialect, Literal)
case class MetadataRec(data: String, metadata: String, id : String)
inline def queryMetadata = query[MetadataRec]
inline given SchemaMeta[MetadataRec] = schemaMeta("tableName", _.id -> "data.id")
val sql = ctx.run(queryMetadata.filter(_.id == lift("?")).map(s => (s.data, s.metadata))).string
````

Expected Compiler to show SQL as follows:

````
SELECT x16.data, x16.metadata FROM tableName x16 WHERE x16.data.id= ?
````

### Actual behavior

Compiler now shows 

````
SELECT x16.data AS _1, x16.metadata AS _2 FROM tableName x16 WHERE x16.data.id = ?
````

This is causing my ability to work with the returned fields by name to fail. 

### Steps to reproduce the behavior

https://scastie.scala-lang.org/qzJCeJncScq0mmkSaQIT7Q

### Workaround

Removed the .map operation and ignore extra fields that are returned.

@getquill/maintainers

**Comment by deusaquilus** [comment]
@jeffgarratt Make a result record and write it to that:
```scala
case class ResultRec(data: String, metadata: String)
ctx.run(queryMetadata.filter(_.id == lift("?")).map(s => ResultRec(s.data, s.metadata))).string
```
After much deliberation thinking, and rethinking I decided to categorically make the output columns have the same names as the fields of the object being decoded. I think this is the only way to sanely comprehend column outputs on the top level.

In previous versions of Quill we had issues with how to deal with queries that had repeated fields in nested (i.e. embedded objects). For example how do you deal with this:
```scala
case class Name(name: String)
case class NameName(name: String, value: Name)
case class Output(nameA: String, nameB: String)
run(
  query[Person].nested
    .map(p => NameName(p.name, Name(p.name))).nested
    .map(nn => Output(nn.name, nn.value.name)
)
```
How is this to be sanely comprehended? The field `name` is mapped multiple times to multiple things and then re-flattened. While that is being done, various things can be appended to it:
```scala
run(
  query[Person].nested
    .map(p => NameName(p.name + "foo", Name(p.name + "bar"))).nested
    .map(nn => Output(nn.name + "A", nn.value.name + "B")
)
```
Furthermore, in ProtoQuill, Output can be part of a coproduct:
```scala
sealed trait OutputTypes
case class Output(nameA: String, nameB: String) extends OutputTypes
case class OutputB(nameA: String) extends OutputTypes
```
Assuming that we have a table-per-coproduct pattern, how do we sanely decode the co-product `OutputTypes`?

In summary, there are two problems that need to be solved here:
1. How do you sanely translate `NameName.value.name` across the subselects resulting from the maps
2. How do you sanely translate them into columns in the output in such a way that co-products can be decoded.

To solve .1, we can append the entire path to an element in each subselect:
```sql
SELECT p.name + 'A', p.valuename + 'B' FROM
  (SELECT p.name AS name , p.name + 'bar' AS valuename FROM Person) AS p
```

The only question now is how to alias the top-level column columns in order to be able to potentially decode multiple kinds of things.

To sanely solve .2 we can make three assumptions:
1) The choice of which coproduct element it will be can be decided by some separate mechanism e.g. a column in p.discriminatorColumn.
2) Each column with the same name means the same value in all the coproducts in which it occurs. For example, `Output.nameA` in output means the same thing as `OutputB.nameA`. Therefore we can make a general query for all the columns in all the things that OutputTypes can be i.e. nameA and nameB
(if any of the things that OutputTypes can be has embedded columns this would be strictly the leaf-fields).
3) Since not every variation of OutputTypes will have all the columns, we need to resolve the columns by name.

TODO Finish

**Comment by jeffgarratt** [comment]
Thank you for the effort and thoughtfulness in this response, greatly appreciated!!  Your efforts in this project are also much appreciated!

**Comment by deusaquilus** [comment]
Thanks for the interest!
